name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libzmq3-dev
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build daemon
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin stored --features server
      - name: Build CLI
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin store-cli
